#!/usr/bin/env python3
"""
generate_index.py -- GCT Physics Engine Build Suite
=====================================================
Automatically generates the Master Index by scanning all content markdown files
for Theorems, Protocols, Definitions, and key section headers.

Usage:
    python build_scripts/generate_index.py
"""

import os
import re
from collections import defaultdict

# Configuration
CONTENT_DIR = "content"
INDEX_OUTPUT = "content/99_Global_Backmatter/03_Master_Index.md"

# Volume/chapter reference mapping
VOLUME_MAP = {
    "00_Global_Frontmatter": "GFM",
    "01_Volume_1_Operating_System": "V1",
    "02_Volume_2_Cosmic_Architecture": "V2",
    "03_Volume_3_Matter_Spectrum": "V3",
    "98_Global_Appendices": "App",
    "99_Global_Backmatter": "GBM",
}

def make_ref(rel_path):
    """Build a short human-readable reference string from a relative path."""
    parts = rel_path.replace("\\", "/").split("/")
    vol = None
    for key, label in VOLUME_MAP.items():
        if parts[0] == key:
            vol = label
            break
    if vol is None:
        return rel_path.replace(".md", "")
    # Try to extract chapter/appendix indicator
    if len(parts) >= 2:
        fname = parts[-1].replace(".md", "")
        # e.g. "Ch11_355keV_Anomaly" -> "Ch11"
        ch_match = re.match(r"(Ch\d+|App_[A-Z]+|\d\d_.*)", fname)
        if ch_match:
            ch = ch_match.group(1)
            # Shorten to just the number/letter
            ch = re.sub(r"^Ch(\d+).*", r"Ch\1", ch)
            ch = re.sub(r"^App_([A-Z]+).*", r"App.\1", ch)
            ch = re.sub(r"^\d\d_(.+)", r"\1", ch)
            return f"{vol}.{ch}"
    return vol


def clean_term(term):
    """Strip LaTeX, markdown bold, and whitespace from a term."""
    term = re.sub(r"\$[^$]+\$", "", term)        # remove inline math
    term = re.sub(r"\*+", "", term)               # remove bold/italic markers
    term = re.sub(r"[(){}\[\]]", "", term)        # remove brackets
    term = term.strip(" .:,;|")
    return term


def generate_index():
    index_map = defaultdict(set)

    # Walk through the content directory
    for root, dirs, files in os.walk(CONTENT_DIR):
        # Skip index files themselves
        dirs.sort()
        for file in sorted(files):
            if not file.endswith(".md"):
                continue
            if "Index" in file or "index" in file:
                continue

            file_path = os.path.join(root, file)
            rel_path = os.path.relpath(file_path, CONTENT_DIR)
            ref = make_ref(rel_path)

            with open(file_path, "r", encoding="utf-8") as f:
                lines = f.readlines()

            for line in lines:
                line = line.rstrip()

                # 1. Bold glossary-style definitions: **Term (...):**
                for match in re.finditer(r"\*\*([A-Z][^*$\n]{2,60}?)\*\*\s*[:(]", line):
                    term = clean_term(match.group(1))
                    if term and len(term) > 3 and not term.isdigit():
                        index_map[term].add(ref)

                # 2. Theorem / Lemma / Corollary / Postulate references
                for match in re.finditer(r"(Theorem|Lemma|Corollary|Postulate)\s+([\d\.A-Z]+)", line):
                    term = f"{match.group(1)} {match.group(2)}"
                    index_map[term].add(ref)

                # 3. Protocol labels: Protocol A, Protocol B-Prime, etc.
                for match in re.finditer(r"Protocol\s+([A-Z][\w\-]*)", line):
                    term = f"Protocol {match.group(1)}"
                    index_map[term].add(ref)

                # 4. Section headers (## level) — key named sections
                hdr = re.match(r"^#{2,4}\s+\*{0,2}([\d\.A-Z][\w\s\(\)\$\\,\-–]{3,60}?)\*{0,2}\s*$", line)
                if hdr:
                    term = clean_term(hdr.group(1))
                    if term and len(term) > 4 and not re.match(r"^\d+$", term):
                        index_map[term].add(ref)

    # Remove trivially short or numeric-only keys
    index_map = {k: v for k, v in index_map.items()
                 if len(k) > 3 and not k.isdigit() and not re.match(r"^[\d\.\s]+$", k)}

    # Sort alphabetically (case-insensitive)
    sorted_terms = sorted(index_map.keys(), key=lambda s: s.lower())

    # Build markdown output
    lines_out = [
        "### **Master Index (Cross-Volume)**\n",
        "\n",
        "*References use volume/chapter shorthand: V1 = Volume 1, V2 = Volume 2, V3 = Volume 3,*\n",
        "*App = Global Appendices, GFM = Global Front Matter, GBM = Global Back Matter.*\n",
        "*This index is auto-generated by `build_scripts/generate_index.py`.*\n",
        "\n",
    ]

    current_letter = ""

    for term in sorted_terms:
        first_letter = re.sub(r"[^A-Za-z]", "", term)
        if not first_letter:
            continue
        first_letter = first_letter[0].upper()

        if first_letter != current_letter:
            current_letter = first_letter
            lines_out.append(f"\n#### **{current_letter}**\n\n")

        refs_str = ", ".join(sorted(index_map[term]))
        lines_out.append(f"*   **{term}:** {refs_str}\n")

    # Write output
    os.makedirs(os.path.dirname(INDEX_OUTPUT), exist_ok=True)
    with open(INDEX_OUTPUT, "w", encoding="utf-8") as f:
        f.writelines(lines_out)

    print(f"SUCCESS: Master Index generated with {len(sorted_terms)} entries -> {INDEX_OUTPUT}")
    return len(sorted_terms)


if __name__ == "__main__":
    generate_index()
