#!/usr/bin/env python3
"""
protocol_o18_trefoil_meridian_trace.py
=======================================

Finite-matrix diagnostic for the trefoil meridian trace identity. This is
an O.18 sanity check, not a closure of the Polaron Unity trefoil case.

PRESENTATION

The trefoil knot group has Wirtinger presentation
    pi_1(S^3 \\ K_trefoil) = < a, b | aba = bab >
(2-bridge form; the third Wirtinger generator c is conjugate to a, b).

A faithful 2-dim representation in SL(2, Z) as an abstract group
representation:
    rho(a) = [[1, 1], [0, 1]]
    rho(b) = [[1, 0], [-1, 1]]

Verification (aba = bab):
    rho(ab)  = [[0, 1], [-1, 1]]
    rho(aba) = [[0, 1], [-1, 0]]
    rho(ba)  = [[1, 1], [-1, 0]]
    rho(bab) = [[0, 1], [-1, 0]]  --  equal, so the relation holds in rho.

MERIDIAN C*-SUBALGEBRA

The meridian subalgebra A_trefoil of C*_r(pi_1) is generated by the
meridian unitaries {a, b} (and their conjugates). The matrices below are
a finite M_2(C) surrogate for the trace identity. They are not unitary:
RHO_A.conj().T @ RHO_A != I and RHO_B.conj().T @ RHO_B != I. Therefore
they do not constitute a unitary finite-dimensional faithful quotient of
the meridian C*-subalgebra.

CANONICAL TRACE

On the finite-matrix surrogate, the trace used for the diagnostic is the
NORMALIZED matrix trace:
    tau(X) = (1/2) Tr(X)
for X in M_2(C).

ZENO CONDITIONAL EXPECTATION

The Zeno conditional expectation E projects onto the abelian
sub-C*-algebra A_diag (the diagonal matrices in M_2(C)):
    E([[a, b], [c, d]]) = [[a, 0], [0, d]]

POLARON UNITY CHECK

The Lemma Y.3.4 identity is:
    tau o E = tau   on the meridian subalgebra.

EXPLICIT VERIFICATION

For an arbitrary X = [[a, b], [c, d]] in M_2(C):
    tau(X) = (a + d) / 2
    E(X) = [[a, 0], [0, d]]
    tau(E(X)) = (a + d) / 2 = tau(X)  ✓

The identity holds exactly on M_2(C), for any matrix entries. In this
protocol that is only a finite-matrix trace-preservation diagnostic; it
does not test a meridian trace identity inside the knot C*-algebra.

REIDEMEISTER-MOVE EXTENSION

By Markov-move invariance of knot-group presentations (Markov 1936;
Birman 1974), Reidemeister moves R-II and R-III on knot diagrams
correspond to conjugation and stabilisation in the braid group. The
trefoil's meridian C*-algebra structure is preserved under these moves
because the canonical trace is conjugation-invariant:
    tau(g X g^(-1)) = tau(X) for any g in the braid group acting on M_2(C).

This protocol verifies the trefoil meridian-trace sub-step only. It does
not prove that the finite-level Polaron knot is fixed inside a slice
{x_n^0} x R^3 of M_n = S^1 x R^3, and it does not construct the
general-prime Anderson-Putnam knot-complement algebra.

POLARON UNITY DISPOSITION

Trefoil-case Polaron Unity is Tier 3 conditional pending resolution of the
App Y finite-level 4-manifold knot-complement clarification (registered as a
sub-closure of Open Problem O.18); the general-prime extension remains Tier 3
conditional on Anderson-Putnam-to-knot-complement extension, canonicity of
K -> A_K, finite-quotient meridian trace construction, and KO-dim-6 sign
verification (O.32).
"""

import json
import numpy as np
from pathlib import Path

try:
    from gct_utils import get_output_path
    OUTPUT_DIR_AVAILABLE = True
except ImportError:
    OUTPUT_DIR_AVAILABLE = False


# Faithful 2-dim SL(2, Z) representation of the trefoil group
RHO_A = np.array([[1, 1], [0, 1]], dtype=np.complex128)
RHO_B = np.array([[1, 0], [-1, 1]], dtype=np.complex128)


def trace_normalised(X):
    """Normalized trace tau(X) = (1/d) Tr(X) for d x d matrices."""
    d = X.shape[0]
    return np.trace(X) / d


def zeno_conditional_expectation(X):
    """Project onto diagonal matrices (abelian subalgebra)."""
    return np.diag(np.diag(X))


def verify_relation_aba_bab(rho_a, rho_b):
    """Verify the Wirtinger relation aba = bab."""
    aba = rho_a @ rho_b @ rho_a
    bab = rho_b @ rho_a @ rho_b
    return np.allclose(aba, bab), aba, bab


def verify_trace_identity_on_test_set():
    """Check tau o E = tau on a representative set of matrices including
    products of meridian generators."""
    rng = np.random.default_rng(seed=42)
    results = []
    test_matrices = [
        ("a", RHO_A),
        ("b", RHO_B),
        ("ab", RHO_A @ RHO_B),
        ("ba", RHO_B @ RHO_A),
        ("aba", RHO_A @ RHO_B @ RHO_A),
        ("bab", RHO_B @ RHO_A @ RHO_B),
        ("a + b", RHO_A + RHO_B),
        ("ab - ba", RHO_A @ RHO_B - RHO_B @ RHO_A),
    ]
    # Add random matrices
    for k in range(5):
        m = rng.standard_normal((2, 2)) + 1j * rng.standard_normal((2, 2))
        test_matrices.append((f"random_{k}", m))

    for name, X in test_matrices:
        tau_X = trace_normalised(X)
        E_X = zeno_conditional_expectation(X)
        tau_E_X = trace_normalised(E_X)
        rel_diff = (abs(tau_X - tau_E_X) / max(abs(tau_X), 1e-12)
                    if abs(tau_X) > 1e-12 else abs(tau_X - tau_E_X))
        results.append({
            "name": name,
            "tau_X": complex(tau_X),
            "tau_E_X": complex(tau_E_X),
            "abs_difference": float(abs(tau_X - tau_E_X)),
            "identity_holds": bool(abs(tau_X - tau_E_X) < 1e-12),
        })
    return results


def conjugation_invariance_check():
    """tau(g X g^(-1)) = tau(X) for braid-group conjugations."""
    # Test with a, b, and their products
    rng = np.random.default_rng(seed=99)
    g_matrices = [RHO_A, RHO_B, RHO_A @ RHO_B, RHO_A @ RHO_B @ RHO_A]
    results = []
    for k in range(5):
        X = rng.standard_normal((2, 2)) + 1j * rng.standard_normal((2, 2))
        for j, g in enumerate(g_matrices):
            g_inv = np.linalg.inv(g)
            gXg_inv = g @ X @ g_inv
            t1 = trace_normalised(X)
            t2 = trace_normalised(gXg_inv)
            results.append({
                "X_index": k,
                "g_index": j,
                "tau_X": complex(t1),
                "tau_gXg_inv": complex(t2),
                "abs_difference": float(abs(t1 - t2)),
                "invariance_holds": bool(abs(t1 - t2) < 1e-10),
            })
    return results


def main():
    print("=" * 76)
    print("O.18 PROTOCOL: Trefoil meridian-subalgebra trace identity")
    print("=" * 76)

    rel_holds, aba, bab = verify_relation_aba_bab(RHO_A, RHO_B)
    print(f"\nFaithful SL(2, Z) representation:")
    print(f"  rho(a) =\n{RHO_A.real.astype(int)}")
    print(f"  rho(b) =\n{RHO_B.real.astype(int)}")
    print(f"\nWirtinger relation check (aba = bab):")
    print(f"  rho(aba) =\n{aba.real.astype(int)}")
    print(f"  rho(bab) =\n{bab.real.astype(int)}")
    print(f"  aba == bab : {rel_holds}")

    print(f"\nTrace-surrogate check (tau o E = tau on finite M_2(C) model):")
    test_results = verify_trace_identity_on_test_set()
    print(f"  {'name':>10}  {'tau(X)':>20}  {'tau(E(X))':>20}  {'diff':>12}  {'holds':>6}")
    for r in test_results:
        print(f"  {r['name']:>10}  {str(r['tau_X']):>20}  "
              f"{str(r['tau_E_X']):>20}  {r['abs_difference']:>12.3e}  "
              f"{str(r['identity_holds']):>6}")

    all_holds = all(r["identity_holds"] for r in test_results)
    print(f"\n  Identity holds for all {len(test_results)} test cases: {all_holds}")

    print(f"\nConjugation invariance (Reidemeister-move foundation):")
    conj_results = conjugation_invariance_check()
    all_invariant = all(r["invariance_holds"] for r in conj_results)
    print(f"  Conjugation invariance for {len(conj_results)} (X, g) pairs: {all_invariant}")

    print(f"\n" + "=" * 76)
    print("VERDICT FOR O.18")
    print("=" * 76)
    if all_holds and all_invariant:
        verdict = ("(i) TRACE SURROGATE verified only: tau o E = tau "
                   "holds on the finite M_2(C) matrix model, whose displayed "
                   "SL(2,Z) matrices are not unitary C*-algebra generators. "
                   "Trefoil-case Polaron Unity remains Tier 3 conditional pending "
                   "construction of a unitary "
                   "finite-dimensional faithful meridian quotient, resolution of the "
                   "App Y finite-level 4-manifold knot-complement clarification "
                   "(registered as a sub-closure of Open Problem O.18), and the "
                   "Y.4.2 direct-product/operator-factor closure; "
                   "the general-prime extension remains Tier 3 conditional on "
                   "Anderson-Putnam-to-knot-complement extension, canonicity of "
                   "K -> A_K, finite-quotient meridian trace construction, and "
                   "KO-dim-6 sign verification (O.32).")
    else:
        verdict = "(ii) Trace identity FAILED on test matrices; closure not yet complete."
    print(f"  {verdict}")
    print("=" * 76)

    out = {
        "wirtinger_presentation": "<a, b | aba = bab>",
        "rho_a": RHO_A.real.tolist(),
        "rho_b": RHO_B.real.tolist(),
        "wirtinger_relation_holds": bool(rel_holds),
        "polaron_unity_identity_holds_for_all_test_cases": bool(all_holds),
        "conjugation_invariance_holds": bool(all_invariant),
        "n_test_cases": len(test_results),
        "n_conjugation_checks": len(conj_results),
        "trace_identity_test_results": [
            {k: (str(v) if isinstance(v, complex) else v) for k, v in r.items()}
            for r in test_results
        ],
        "trace_surrogate_verified": bool(all_holds and all_invariant),
        "verdict_closed": False,
        "closure_status": "TRACE_SURROGATE_ONLY__O18_REMAINS_OPEN",
        "verdict_text": verdict,
    }
    if OUTPUT_DIR_AVAILABLE:
        out_path = get_output_path("protocol_o18_trefoil_meridian_trace_results.json")
    else:
        out_path = Path(__file__).resolve().parent.parent / "data" / "protocol_o18_trefoil_meridian_trace_results.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nResults saved to: {out_path}")
    print("=" * 76)


if __name__ == "__main__":
    main()
