#!/usr/bin/env python3
"""
protocol_w6_strong_cp_holonomy.py - W6: finite witness for theta-bar = 0
========================================================================
App FM P.32 states GCT predicts the strong-CP angle theta-bar = 0 exactly "from
icosahedral chirality-preserving cycle closure (all 5/3/2-fold I_h rotations
close at multiples of 2pi exactly)", with theorem-grade elevation bundled into
O.5 (QLQCD-1L). W6 supplies the FINITE, decidable part of that mechanism.

Two witnesses:

  W6-a (2pi cycle closure): every element of the icosahedral rotation group I
  (60 SO(3) matrices) has order in {1,2,3,5}; g^order = identity exactly, i.e.
  the 5/3/2-fold rotations close at exact 2pi multiples (rotation angle * order
  in 2pi Z). This is the literal P.32 statement.

  W6-b (no geometric CP character -- the load-bearing witness): a CP phase
  assigned to icosahedral holonomy would be a group homomorphism chi: I -> U(1)
  (a 1-dimensional representation / character). The icosahedral rotation group
  I ~ A_5 is PERFECT: its commutator subgroup [I,I] equals I, so its
  abelianization I^ab is trivial and the ONLY homomorphism I -> U(1) is trivial
  (chi = 1). Hence the icosahedral symmetry admits NO non-trivial CP character:
  it cannot SOURCE or GENERATE a geometric strong-CP phase through its holonomy.
  This is convention-independent (any U(1) character of a perfect group is
  trivial) and theorem-grade as a finite-group statement.

  SCOPE (do not overclaim): this is a NECESSARY condition, not a proof that the
  full QCD theta-bar = theta_bare + arg(det M_q) vanishes. Perfectness shows the
  icosahedral symmetry generates no geometric theta-phase; it does not exclude a
  bare theta inserted by hand, nor does it address the chiral-anomaly quark-mass
  phase. The bridge identifying the physical theta-bar with the (trivial)
  icosahedral character -- the full anomaly-free topological-sector argument --
  remains O.5, so P.32 stays Tier 3.

We verify perfectness by direct computation: the subgroup generated by all
commutators [a,b] = a b a^{-1} b^{-1} is the whole group.
"""

import json
import os
import sys
import io

import numpy as np

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

_SRC = os.path.dirname(os.path.abspath(__file__))
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

try:
    from gct_utils import get_output_path
except ImportError:
    def get_output_path(fn):
        return os.path.join(_SRC, "..", "data", fn)

from protocol_cage_repair import (
    vertex_pairs_from_projection, icosahedral_rotations_lattice_frame,
)

TOL = 1e-6


def key(M):
    return tuple(np.round(np.asarray(M, float) / TOL).astype(np.int64).ravel())


def build_group():
    vp, _ = vertex_pairs_from_projection()
    mats = [np.asarray(m, float) for m in icosahedral_rotations_lattice_frame(vp)]
    return mats


def element_order(M, identity, max_ord=12):
    P = M.copy()
    for n in range(1, max_ord + 1):
        if np.allclose(P, identity, atol=1e-6):
            return n
        P = P @ M
    return None


def rotation_angle(M):
    """SO(3) rotation angle from trace: tr = 1 + 2 cos(theta)."""
    c = (np.trace(M) - 1.0) / 2.0
    c = max(-1.0, min(1.0, c))
    return float(np.degrees(np.arccos(c)))


def generated_subgroup(seeds, all_keys_to_mat):
    """Close the set generated by `seeds` (list of matrices) under multiplication
    within the ambient group; return set of keys."""
    I = np.eye(3)
    closure = {key(I): I}
    frontier = [I] + list(seeds)
    for s in seeds:
        closure[key(s)] = s
    changed = True
    while changed:
        changed = False
        elems = list(closure.values())
        for a in elems:
            for b in seeds:
                p = a @ b
                k = key(p)
                if k not in closure:
                    closure[k] = p
                    changed = True
    return set(closure.keys())


def run():
    print("=" * 70)
    print("GCT Protocol W6 - finite witness for strong-CP theta-bar = 0")
    print("=" * 70)

    G = build_group()
    I = np.eye(3)
    n = len(G)
    print(f"\n  Icosahedral rotation group I: {n} proper rotations (det +1)")

    # W6-a: orders and 2pi closure
    orders = {}
    closure_exact = True
    angle_by_order = {}
    for M in G:
        o = element_order(M, I)
        orders[o] = orders.get(o, 0) + 1
        ang = rotation_angle(M)
        angle_by_order.setdefault(o, set()).add(round(ang, 2))
        # g^order == I exactly => angle * order is a multiple of 360 deg
        Po = np.linalg.matrix_power(M, o) if o else None
        if o is None or not np.allclose(Po, I, atol=1e-6):
            closure_exact = False
    orders_ok = set(orders.keys()) <= {1, 2, 3, 5}
    print(f"\n  W6-a  element-order histogram: "
          f"{ {k: orders[k] for k in sorted(orders)} }")
    print(f"        orders subset of {{1,2,3,5}}: {orders_ok}; "
          f"every g^order = I (to 1e-6 tolerance): {closure_exact}")
    for o in sorted(angle_by_order):
        print(f"        order {o}: rotation angle(s) {sorted(angle_by_order[o])} deg "
              f"-> angle*order = {sorted({round(a*o) for a in angle_by_order[o]})} deg "
              f"(360 multiples)")

    # W6-b: perfectness => trivial abelianization => no nontrivial U(1) character
    all_keys = {key(M): M for M in G}
    commutators = []
    seen = set()
    for a in G:
        ainv = a.T  # rotation inverse = transpose
        for b in G:
            binv = b.T
            c = a @ b @ ainv @ binv
            k = key(c)
            if k not in seen:
                seen.add(k)
                commutators.append(c)
    comm_subgroup = generated_subgroup(commutators, all_keys)
    perfect = (comm_subgroup == set(all_keys.keys()))   # set equality, not just |.|
    n_distinct_commutators = len(commutators)
    print(f"\n  W6-b  distinct commutators [a,b]: {n_distinct_commutators}")
    print(f"        commutator subgroup [I,I] order: {len(comm_subgroup)} "
          f"(group order {n})")
    print(f"        I is PERFECT ([I,I]=I): {perfect}  ->  abelianization trivial "
          f"->  only homomorphism I->U(1) is trivial")

    no_geometric_cp_character = perfect
    print("\n  " + "-" * 64)
    verdict = (
        "The icosahedral symmetry admits NO non-trivial CP character -- it cannot "
        "source a geometric strong-CP phase. (W6-a) all 5/3/2-fold rotations close "
        "at 2pi multiples (orders in {1,2,3,5}, g^order = I to 1e-6 tolerance), the "
        "literal P.32 statement. (W6-b, load-bearing, theorem-grade as a finite-"
        "group fact) the icosahedral rotation group I ~ A_5 is PERFECT ([I,I] = I, "
        "verified by set-equality closure of all commutators), so its "
        "abelianization is trivial and the only homomorphism I -> U(1) is the "
        "trivial character; the icosahedral holonomy can carry no non-trivial CP "
        "phase. SCOPE: this is a NECESSARY condition, not a proof of the full QCD "
        "theta-bar = theta_bare + arg(det M_q) = 0 -- it excludes a "
        "geometrically-sourced theta-phase but not a bare insertion or the "
        "chiral-anomaly quark-mass phase. The bridge identifying the physical "
        "theta-bar with the trivial icosahedral character remains O.5, so P.32 "
        "stays Tier 3."
        if (perfect and orders_ok and closure_exact) else
        "Witness incomplete -- review (group structure or perfectness check failed).")
    print("  VERDICT:", verdict)
    print("=" * 70)

    results = {
        "group_order": n,
        "W6a_order_histogram": {int(k): orders[k] for k in sorted(orders) if k},
        "W6a_orders_subset_1235": bool(orders_ok),
        "W6a_all_g_pow_order_identity_tol1e-6": bool(closure_exact),
        "W6b_n_distinct_commutators": n_distinct_commutators,
        "W6b_commutator_subgroup_order": len(comm_subgroup),
        "W6b_is_perfect_set_equality": bool(perfect),
        "W6b_abelianization_trivial": bool(perfect),
        "W6b_no_geometric_cp_character": bool(no_geometric_cp_character),
        "full_theta_bar_zero_proven": False,
        "full_theta_bar_residual": "theta_bare insertion + chiral-anomaly arg(det M_q) bridge",
        "theorem_grade_proof_bundles_with": "O.5 (QLQCD-1L)",
        "P32_tier": "Tier 3 (mechanism + finite no-CP-character necessary condition; full proof O.5)",
        "verdict": verdict,
    }
    out = get_output_path("protocol_w6_strong_cp_holonomy_results.json")
    with open(out, "w") as fp:
        json.dump(results, fp, indent=2)
    print(f"\n[Saved JSON] -> {out}")
    return results


if __name__ == "__main__":
    run()
