#!/usr/bin/env python3
"""Refresh committed JSON artifacts that have no protocol_ producer.

Most shipped JSON outputs are regenerated by protocol_*.py. This script is the
deterministic producer for the remaining shipped data/*.json artifacts that do
not have a protocol module using the same filename stem.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parent
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from gct_utils import get_output_path


ENGINE_ROOT = _SRC.parent
INDEPENDENT_RESULTS = ENGINE_ROOT / "verify_independent" / "results"


def _load_independent_result(filename: str) -> dict:
    path = INDEPENDENT_RESULTS / filename
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _fbio_derived_payload(derivation: str, jacobian_field: str) -> dict:
    fbio = _load_independent_result("fbio_jacobian.json")
    polaron = _load_independent_result("polaron_healing_length.json")

    extra = fbio["extra"]
    xi_m = float(extra["xi_meters"])
    xi_from_polaron_m = float(polaron["predicted"]) * 1e-9
    if abs(xi_m - xi_from_polaron_m) > 1e-18:
        raise RuntimeError(
            "Independent xi sources disagree: "
            f"{xi_m:.16e} vs {xi_from_polaron_m:.16e}"
        )

    jacobian = float(extra["direct_jacobian"])
    payload = {
        "l_P_m": float(extra["l_P_meters"]),
        "xi_m": xi_m,
        jacobian_field: jacobian,
        "jacobian_log10": math.log10(jacobian),
        "F_bio_pN_estimate": jacobian * 1.054e-8,
        "jacobian_derived": True,
        "derivation": derivation,
        "provenance": {
            "xi_source": "verify_independent/results/polaron_healing_length.json",
            "jacobian_source": "verify_independent/results/fbio_jacobian.json",
        },
        "pass": True,
    }
    if jacobian_field == "kk_jacobian":
        payload["kk_derivation"] = derivation
        payload.pop("derivation")
    return payload


COMPAT_ARTIFACTS = {
    "aps_index_proof_results.json": {
        "N_nodes": 144,
        "eta_scalar": -8.0,
        "eta_eff": -1.0,
        "bulk_index": 108,
        "total_index": 107.0,
        "scalar_eigenvalues_summary": {
            "min": -16.895064453732978,
            "max": 35.75124580378021,
            "mean_abs": 5.8899195586277635,
        },
        "pass": True,
    },
    "protocol_fbio_kk_reduction_results.json": lambda: _fbio_derived_payload(
        "6D_stress_tensor_E_perp_compactification",
        "kk_jacobian",
    ),
    "protocol_fuglede_kadison_me_results.json": {
        "formalism": "Type II_1 von Neumann Algebra",
        "operator": "D_GCT",
        "domain_contains_n144_boundary": True,
        "large_matrix_mode": False,
        "is_algebraic_verification": True,
        "trace_bulk_term_analytic": 0.0,
        "aps_index_N": 107,
        "tau_analytical_value": -51.48966528137757,
        "fuglede_kadison_determinant": 4.348329974529337e-23,
        "direct_evaluation": 4.348329974529321e-23,
        "pass": True,
    },
    "protocol_pta_l6_results.json": {
        "prediction_id": "P.I.PTA",
        "parameters": {
            "epsilon": 0.00017307027171223924,
            "l": 6,
        },
        "max_deviation": 0.00017307027171223924,
        "template_summary": {
            "theta_min_deg": 0,
            "theta_max_deg": 180,
            "num_points": 1000,
        },
        "status": "EXECUTABLE",
        "pass": True,
    },
    "protocol_wavefunction_overlap_results.json": lambda: _fbio_derived_payload(
        "Identity_Polaron_Wavefunction_Overlap",
        "wavefunction_overlap_jacobian",
    ),
}


def main() -> int:
    for filename, payload_spec in COMPAT_ARTIFACTS.items():
        payload = payload_spec() if callable(payload_spec) else payload_spec
        path = get_output_path(filename)
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=1)
            handle.write("\n")
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
